import type { RoadmapItem, TotalScore, RoadmapPriority, RoadmapQuarter, RoadmapYear } from "@/lib/scan/types";
import { pillars } from "@/lib/scan/definition/pillars";
import { maturityLevels } from "@/lib/scan/definition/maturity-levels";

type GapAnalysis = {
  pillarCode: string;
  subDimensionCode: string;
  label: string;
  currentLevel: number;
  targetLevel: number;
  gap: number;
  priority: RoadmapPriority;
};

function calculateGaps(scores: TotalScore, targetLevel: number = 4): GapAnalysis[] {
  const gaps: GapAnalysis[] = [];

  for (const pillar of scores.pillars) {
    for (const subDim of pillar.subDimensions) {
      if (subDim.score === 0 || subDim.questionCount === 0) continue;

      const currentLevel = Math.round(subDim.score);
      const gap = targetLevel - currentLevel;

      if (gap > 0) {
        // Determine priority based on gap size and pillar importance
        let priority: RoadmapPriority = "low";
        if (gap >= 3) priority = "high";
        else if (gap >= 2) priority = "medium";

        gaps.push({
          pillarCode: pillar.code,
          subDimensionCode: subDim.code,
          label: subDim.label,
          currentLevel,
          targetLevel,
          gap,
          priority,
        });
      }
    }
  }

  // Sort by priority (high first) then by gap size
  return gaps.sort((a, b) => {
    const priorityOrder = { high: 0, medium: 1, low: 2 };
    if (priorityOrder[a.priority] !== priorityOrder[b.priority]) {
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    }
    return b.gap - a.gap;
  });
}

function getActionTitle(subDimensionLabel: string, currentLevel: number, targetLevel: number): string {
  const currentLevelInfo = maturityLevels.find((l) => l.level === currentLevel);
  const targetLevelInfo = maturityLevels.find((l) => l.level === targetLevel);

  return `${subDimensionLabel}: van ${currentLevelInfo?.shortLabel || currentLevel} naar ${targetLevelInfo?.shortLabel || targetLevel}`;
}

function getActionDescription(pillarCode: string, subDimensionCode: string, currentLevel: number): string {
  // Generic descriptions based on level
  const descriptions: Record<number, string> = {
    1: "Breng de basis op orde. Definieer processen, verantwoordelijkheden en standaarden.",
    2: "Standaardiseer en documenteer. Zorg voor consistente werkwijzen en meetbare resultaten.",
    3: "Integreer en optimaliseer. Verbind processen en systemen voor proactieve sturing.",
    4: "Verfijn en automatiseer. Focus op continue verbetering en voorspellende inzichten.",
  };

  return descriptions[currentLevel] || "Werk aan verdere optimalisatie en integratie.";
}

function assignToTimeline(gaps: GapAnalysis[]): { gap: GapAnalysis; quarter: RoadmapQuarter; year: RoadmapYear }[] {
  const timeline: { gap: GapAnalysis; quarter: RoadmapQuarter; year: RoadmapYear }[] = [];
  
  const quarters: RoadmapQuarter[] = ["Q1", "Q2", "Q3", "Q4"];
  let quarterIndex = 0;
  let year: RoadmapYear = 1;

  for (const gap of gaps) {
    // High priority items go in year 1
    // Medium priority items go in year 1-2
    // Low priority items go in year 2-3
    if (gap.priority === "high") {
      year = 1;
    } else if (gap.priority === "medium") {
      year = quarterIndex >= 4 ? 2 : 1;
    } else {
      year = quarterIndex >= 8 ? 3 : 2;
    }

    const quarter = quarters[quarterIndex % 4];
    timeline.push({ gap, quarter, year });

    quarterIndex++;
  }

  return timeline;
}

export function generateRoadmap(scores: TotalScore, targetLevel: number = 4): RoadmapItem[] {
  const gaps = calculateGaps(scores, targetLevel);
  const timeline = assignToTimeline(gaps);

  return timeline.map(({ gap, quarter, year }, index) => ({
    id: `roadmap-${index + 1}`,
    pillarCode: gap.pillarCode,
    subDimensionCode: gap.subDimensionCode,
    title: getActionTitle(gap.label, gap.currentLevel, gap.targetLevel),
    description: getActionDescription(gap.pillarCode, gap.subDimensionCode, gap.currentLevel),
    currentLevel: gap.currentLevel,
    targetLevel: gap.targetLevel,
    quarter,
    year,
    priority: gap.priority,
    isAutoGenerated: true,
    isCompleted: false,
  }));
}

// Generate demo roadmap for visualization
export function generateDemoRoadmap(): RoadmapItem[] {
  return [
    {
      id: "roadmap-1",
      pillarCode: "afas_modules",
      subDimensionCode: "crm",
      title: "CRM: van Basis naar Gedefinieerd",
      description: "Standaardiseer CRM-processen en implementeer automatische lead tracking.",
      currentLevel: 2,
      targetLevel: 3,
      quarter: "Q1",
      year: 1,
      priority: "high",
      isAutoGenerated: true,
      isCompleted: false,
    },
    {
      id: "roadmap-2",
      pillarCode: "integraties",
      subDimensionCode: "data_uitwisseling",
      title: "Data-uitwisseling: van Basis naar Gedefinieerd",
      description: "Implementeer gestructureerde API-koppelingen en data validatie.",
      currentLevel: 2,
      targetLevel: 3,
      quarter: "Q2",
      year: 1,
      priority: "high",
      isAutoGenerated: true,
      isCompleted: false,
    },
    {
      id: "roadmap-3",
      pillarCode: "rapportage_data",
      subDimensionCode: "management_info",
      title: "Managementinformatie: van Basis naar Gedefinieerd",
      description: "Bouw KPI-dashboards en implementeer geautomatiseerde rapportages.",
      currentLevel: 2,
      targetLevel: 3,
      quarter: "Q3",
      year: 1,
      priority: "medium",
      isAutoGenerated: true,
      isCompleted: false,
    },
    {
      id: "roadmap-4",
      pillarCode: "organisatie_maturiteit",
      subDimensionCode: "processen",
      title: "Processen & Werkwijzen: van Basis naar Gedefinieerd",
      description: "Documenteer en standaardiseer kernprocessen over de organisatie.",
      currentLevel: 2,
      targetLevel: 3,
      quarter: "Q4",
      year: 1,
      priority: "medium",
      isAutoGenerated: true,
      isCompleted: false,
    },
    {
      id: "roadmap-5",
      pillarCode: "rapportage_data",
      subDimensionCode: "data_kwaliteit",
      title: "Data kwaliteit & Governance: van Basis naar Gedefinieerd",
      description: "Implementeer data governance framework en kwaliteitscontroles.",
      currentLevel: 2,
      targetLevel: 3,
      quarter: "Q1",
      year: 2,
      priority: "medium",
      isAutoGenerated: true,
      isCompleted: false,
    },
    {
      id: "roadmap-6",
      pillarCode: "organisatie_maturiteit",
      subDimensionCode: "competenties",
      title: "Competenties & Vaardigheden: van Basis naar Gedefinieerd",
      description: "Ontwikkel trainingsplan en skill matrix voor digitale vaardigheden.",
      currentLevel: 2,
      targetLevel: 3,
      quarter: "Q2",
      year: 2,
      priority: "low",
      isAutoGenerated: true,
      isCompleted: false,
    },
  ];
}
