import type { QuestionDefinition } from "./types";

export const questions: QuestionDefinition[] = [
  {
    key: "customer_name",
    sectionCode: "profile_basis",
    order: 10,
    label: "Klantnaam",
    helpText: "Vul de naam van de organisatie in.",
    inputType: "text",
    required: true,
    placeholder: "Bijvoorbeeld: Janssen BV",
  },
  {
    key: "sector",
    sectionCode: "profile_basis",
    order: 20,
    label: "Sector",
    helpText: "Kies de sector die het best past.",
    inputType: "single_select",
    required: true,
    optionSetKey: "sector_options",
    examples: [
      "Bijvoorbeeld: zorg, onderwijs of commercieel",
      "Kies de sector die processen en inrichting het meest bepaalt",
    ],
  },
  {
    key: "organization_size",
    sectionCode: "profile_basis",
    order: 30,
    label: "Organisatiegrootte",
    helpText: "Kies de klasse die het best past.",
    inputType: "single_select",
    required: true,
    optionSetKey: "organization_size_options",
    examples: [
      "Denk aan het totaal aantal medewerkers",
      "Kies de huidige omvang van de organisatie",
    ],
  },
  {
    key: "administration_count",
    sectionCode: "profile_basis",
    order: 40,
    label: "Aantal administraties / entiteiten",
    helpText: "Kies wat het best past bij de scope.",
    inputType: "single_select",
    required: true,
    optionSetKey: "administration_count_options",
    examples: [
      "Denk aan bv’s of aparte administraties",
      "Kies alleen wat binnen deze scan valt",
    ],
  },
  {
    key: "organization_type",
    sectionCode: "profile_basis",
    order: 45,
    label: "Type organisatie en operatie",
    helpText:
      "Kies de omschrijvingen die passen bij de manier waarop de organisatie werkt.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "organization_type_options",
    examples: [
      "Kies meerdere opties als de organisatie op meerdere manieren werkt",
      "Selecteer alleen wat echt iets zegt over structuur en operatie",
    ],
  },
  {
    key: "afas_products",
    sectionCode: "profile_afas",
    order: 10,
    label: "Gebruikte AFAS-onderdelen",
    helpText: "Kies alles wat nu in gebruik of relevant is.",
    inputType: "multi_select",
    required: false,
    optionSetKey: "afas_products_options",
    examples: [
      "Bijvoorbeeld: Financieel, HRM, Inkoop of Workflow",
      "Kies ook onderdelen die relevant zijn voor deze scan",
    ],
  },
  {
    key: "ownership_model",
    sectionCode: "profile_afas",
    order: 20,
    label: "Wie is verantwoordelijk voor wijzigingen in AFAS?",
    helpText:
      "Kies hoe het beheer van AFAS nu is georganiseerd.",
    inputType: "single_select",
    required: true,
    optionSetKey: "ownership_model_options",
    allowsComment: true,
    examples: [
      "Intern beheer, key-users, of uitbesteed?",
      "Wie pakt wijzigingsverzoeken op?",
    ],
  },
  {
    key: "afas_usage_duration",
    sectionCode: "profile_afas",
    order: 30,
    label: "Sinds wanneer gebruikt de organisatie AFAS?",
    helpText: "Kies hoe lang AFAS al in gebruik is binnen de organisatie.",
    inputType: "single_select",
    required: true,
    optionSetKey: "afas_usage_duration_options",
    allowsComment: true,
    examples: [
      "Een oudere inrichting kent vaak andere keuzes en meer historie",
      "Kijk naar het moment waarop AFAS echt in gebruik is genomen",
    ],
  },
  {
    key: "maintenance_quality",
    sectionCode: "profile_afas",
    order: 40,
    label: "Hoe goed is de inrichting de afgelopen jaren onderhouden?",
    helpText:
      "Kies hoe goed beheer, opschoning en wijzigingen de afgelopen jaren zijn bijgehouden.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maintenance_quality_options",
    allowsComment: true,
    examples: [
      "Denk aan beheer, documentatie, opschoning en gecontroleerde wijzigingen",
      "Kijk niet alleen naar techniek, maar ook naar procesafspraken en discipline",
    ],
  },
  {
    key: "expected_org_changes",
    sectionCode: "profile_afas",
    order: 50,
    label: "Worden in de komende jaren fusies, overnames of afsplitsingen verwacht?",
    helpText:
      "Kies of er verwachte organisatieveranderingen zijn die impact kunnen hebben op inrichting, beheer of administraties.",
    inputType: "single_select",
    required: true,
    optionSetKey: "expected_org_changes_options",
    allowsComment: true,
    examples: [
      "Denk aan fusies, overnames, afsplitsingen of sterke groei in entiteiten",
      "Kijk vooral naar veranderingen die invloed hebben op structuur en inrichting",
    ],
  },
  {
    key: "standardization_context",
    sectionCode: "profile_afas",
    order: 60,
    label: "Hoeveel maatwerk zit er in de AFAS-inrichting?",
    helpText:
      "Kies in hoeverre jullie AFAS-inrichting afwijkt van de standaard.",
    inputType: "single_select",
    required: true,
    optionSetKey: "standardization_context_options",
    allowsComment: true,
    examples: [
      "Veel maatwerk = veel afwijkende inrichtingen en scripts",
      "Standaard = dicht bij de AFAS-standaard gebleven",
    ],
  },
  {
    key: "primary_process_chains",
    sectionCode: "profile_afas",
    order: 70,
    label: "Belangrijkste procesketens",
    helpText: "Kies de ketens die nu het belangrijkst zijn.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "primary_process_chains_options",
    examples: [
      "Bijvoorbeeld: order tot factuur of inkoop tot betaling",
      "Kies alleen de ketens die echt centraal staan",
    ],
  },

  {
    key: "scan_reason",
    sectionCode: "profile_reason",
    order: 10,
    label: "Aanleiding en doel van de scan",
    helpText: "Kies de belangrijkste reden voor deze scan.",
    inputType: "single_select",
    required: true,
    optionSetKey: "scan_reason_options",
    examples: [
      "Bijvoorbeeld: nulmeting, optimalisatie of herinrichting",
      "Kies wat nu het zwaarst weegt",
    ],
  },
  {
    key: "biggest_bottleneck",
    sectionCode: "profile_reason",
    order: 20,
    label: "Belangrijkste knelpunten op dit moment",
    helpText: "Kies de onderwerpen die nu het meest knellen.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "biggest_bottleneck_options",
    examples: [
      "Bijvoorbeeld: processen, eigenaarschap of rapportage",
      "Kies alleen wat nu echt de meeste druk geeft",
    ],
  },
  // NIEUWE VRAGEN - Aanleiding verdieping
  {
    key: "scan_reason_detailed",
    sectionCode: "profile_reason",
    order: 25,
    label: "Wat is de belangrijkste reden dat deze scan nu wordt gedaan?",
    helpText: "Kies wat het beste past bij de aanleiding.",
    inputType: "single_select",
    required: true,
    optionSetKey: "scan_reason_detailed_options",
    allowsComment: true,
    examples: [
      "Denk aan de directe aanleiding of trigger",
      "Wat maakte dat dit nu nodig is?",
    ],
  },
  {
    key: "improvement_urgency",
    sectionCode: "profile_reason",
    order: 30,
    label: "Hoe urgent is verbetering?",
    helpText: "Geef aan hoe snel verbetering nodig is.",
    inputType: "single_select",
    required: true,
    optionSetKey: "improvement_urgency_options",
    allowsComment: true,
    dimensionCode: "urgency",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Is er directe druk of is het meer wenselijk?",
      "Blokkeren problemen de dagelijkse operatie?",
    ],
  },

  // Scope section - "scope" (Breedte) vraag verwijderd wegens overlap met scope_depth
  {
    key: "scope_focus",
    sectionCode: "scope",
    order: 10,
    label: "Belangrijkste focusgebieden",
    helpText: "Kies de gebieden die nu de meeste aandacht vragen.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "scope_focus_options",
    examples: [
      "Bijvoorbeeld: processen, AFAS-inrichting of rapportage",
      "Kies waar de scan extra scherpte op moet geven",
    ],
  },
  {
    key: "scope_depth",
    sectionCode: "scope",
    order: 20,
    label: "Gewenst detailniveau",
    helpText: "Kies hoe diep je wilt kijken.",
    inputType: "single_select",
    required: true,
    optionSetKey: "scope_depth_options",
    examples: [
      "Eerste beeld = snel en globaal",
      "Verbeterplan = meer detail en houvast",
    ],
  },

  {
    key: "ownership_clarity",
    sectionCode: "diagnose",
    order: 10,
    label: "Eigenaarschap van processen en inrichting",
    helpText: "Hoe duidelijk is het eigenaarschap nu?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_clarity_options",
    allowsComment: true,
    dimensionCode: "governance",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Weet iedereen wie beslist over wijzigingen?",
      "Is helder wie eigenaar is van een proces?",
    ],
  },
  {
    key: "change_decision_process",
    sectionCode: "diagnose",
    order: 20,
    label: "Besluitvorming over wijzigingen",
    helpText: "Hoe worden wijzigingen nu besloten?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_change_governance_options",
    allowsComment: true,
    dimensionCode: "governance",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Via een vast overleg of meer ad hoc?",
      "Is er een duidelijke route voor wijzigingsverzoeken?",
    ],
  },
  {
    key: "improvement_governance",
    sectionCode: "diagnose",
    order: 30,
    label: "Sturing op verbetering",
    helpText: "Hoe structureel wordt er op verbetering gestuurd?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_improvement_options",
    allowsComment: true,
    dimensionCode: "governance",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Worden knelpunten actief opgepakt?",
      "Is er een vast ritme voor verbeteren?",
    ],
  },
  {
    key: "process_standardization",
    sectionCode: "diagnose",
    order: 40,
    label: "Eenduidigheid van werkwijze",
    helpText: "Hoe eenduidig verlopen de belangrijkste processen?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_standardization_options",
    allowsComment: true,
    dimensionCode: "processes",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Werken teams op dezelfde manier?",
      "Of verschilt dit per persoon of afdeling?",
    ],
  },
  {
    key: "exception_control",
    sectionCode: "diagnose",
    order: 50,
    label: "Omgaan met uitzonderingen",
    helpText: "Hoe beheersbaar zijn uitzonderingen nu?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_exception_control_options",
    allowsComment: true,
    dimensionCode: "processes",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Zijn afwijkingen vast en beheersbaar?",
      "Of worden ze vaak handmatig opgelost?",
    ],
  },
  {
    key: "issue_resolution",
    sectionCode: "diagnose",
    order: 60,
    label: "Structureel oplossen van knelpunten",
    helpText: "Hoe pak je terugkerende problemen aan?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_issue_resolution_options",
    allowsComment: true,
    dimensionCode: "improvement",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Wordt alleen het symptoom opgelost?",
      "Of pak je ook de oorzaak aan?",
    ],
  },

  {
    key: "process_documentation",
    sectionCode: "diagnose",
    order: 55,
    label: "Vastlegging van werkafspraken",
    helpText: "Hoe goed zijn werkwijze en afspraken vastgelegd?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_clarity_options",
    allowsComment: true,
    dimensionCode: "processes",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Zijn processtappen ergens beschreven?",
      "Of zit de kennis vooral in hoofden?",
    ],
  },

  {
    key: "finance_strategic_pressure",
    sectionCode: "diagnose",
    order: 101,
    label: "Waar ervaar je nu de meeste problemen binnen financieel?",
    helpText:
      "Kies waar binnen financieel nu de meeste druk zit.",
    inputType: "single_select",
    required: true,
    optionSetKey: "finance_strategic_pressure_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "finance",
    category: "AFAS Modules",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Betrouwbaarheid van data, uitzonderingen of stuurinformatie?",
      "Kies wat nu het meeste effect heeft",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "financieel" },
    ],
  },
  {
    key: "finance_foundation_reliability",
    sectionCode: "diagnose",
    order: 110,
    label: "Hoe betrouwbaar zijn de financiële basisgegevens?",
    helpText: "Denk aan grootboek, dagboeken en stamdata.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_strength_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "finance",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Kun je blind vertrouwen op de cijfers?",
      "Of twijfel je regelmatig aan de betrouwbaarheid?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "financieel" },
    ],
  },
  {
    key: "finance_exception_handling",
    sectionCode: "diagnose",
    order: 120,
    label: "Uitzonderingen in financiële verwerking",
    helpText: "Kies hoe beheersbaar financiële afwijkingen nu zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_exception_practical_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "finance",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan correcties, memoriaal of afwijkende facturen",
      "Worden deze vast opgevangen of steeds opnieuw opgelost?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "financieel" },
    ],
  },
  {
    key: "finance_reporting_maturity",
    sectionCode: "diagnose",
    order: 130,
    label: "Financiële stuurinformatie",
    helpText: "Kies hoe bruikbaar de financiële rapportage nu is.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_usefulness_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "finance",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan tijdigheid, betrouwbaarheid en definities",
      "Kun je hier echt op sturen?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "financieel" },
      {
        field: "scope_focus",
        operator: "includes",
        value: "rapportage_sturing",
      },
    ],
  },

  {
    key: "order_strategic_pressure",
    sectionCode: "diagnose",
    order: 205,
    label: "Waar ervaar je nu de meeste problemen binnen ordermanagement?",
    helpText:
      "Kies waar binnen ordermanagement nu de meeste druk zit.",
    inputType: "single_select",
    required: true,
    optionSetKey: "order_strategic_pressure_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "ordermanagement",
    category: "AFAS Modules",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Orderinvoer, levering, blokkades of facturatie?",
      "Kies wat nu het meeste effect heeft",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "ordermanagement" },
    ],
  },
  {
    key: "order_flow_standardization",
    sectionCode: "diagnose",
    order: 210,
    label: "Eenduidigheid van de orderroute",
    helpText: "Kies hoe eenduidig order naar levering en factuur verloopt.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_standardization_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "ordermanagement",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan orderinvoer, blokkades, levering en facturatie",
      "Werkt iedereen vanuit dezelfde route?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "ordermanagement" },
    ],
  },
  {
    key: "order_exception_complexity",
    sectionCode: "diagnose",
    order: 220,
    label: "Afwijkingen in orderafhandeling",
    helpText: "Kies hoe vaak het orderproces afwijkt en hoe beheersbaar dat is.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_exception_control_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "ordermanagement",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan prijsafspraken of handmatige ingrepen",
      "Zijn afwijkingen standaard voorzien of vooral noodoplossingen?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "ordermanagement" },
    ],
  },
  {
    key: "order_system_fit",
    sectionCode: "diagnose",
    order: 230,
    label: "Aansluiting tussen orderproces en AFAS-inrichting",
    helpText: "Kies hoe goed AFAS de gewenste orderroute ondersteunt.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_fit_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "ordermanagement",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan statussen, blokkades en factuurmomenten",
      "Sluit de gewenste route goed aan op AFAS?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "ordermanagement" },
      {
        field: "scope_focus",
        operator: "includes",
        value: "afas_inrichting_gebruik",
      },
    ],
  },

  {
    key: "care_registration_exceptions",
    sectionCode: "diagnose",
    order: 310,
    label: "Uitzonderingen in registratie of declaratie",
    helpText: "Kies hoe beheersbaar deze afwijkingen nu zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_exception_control_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "care",
    category: "Branchespecifiek",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan correcties of afwijkende registraties",
      "Moet er vaak handmatig worden hersteld?",
    ],
    visibleWhen: [{ field: "sector", operator: "equals", value: "zorg" }],
  },
  {
    key: "care_accountability_pressure",
    sectionCode: "diagnose",
    order: 320,
    label: "Ondersteuning van verantwoording",
    helpText: "Hoe goed ondersteunen je processen de verantwoording?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_usefulness_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "care",
    category: "Branchespecifiek",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Heb je snel de juiste informatie voor controles?",
      "Of kost dit veel uitzoekwerk?",
    ],
    visibleWhen: [
      { field: "sector", operator: "equals", value: "zorg" },
      {
        field: "scope_focus",
        operator: "includes",
        value: "rapportage_sturing",
      },
    ],
  },
  {
    key: "care_process_standardization",
    sectionCode: "diagnose",
    order: 325,
    label: "Eenduidigheid van zorgprocessen",
    helpText: "Hoe eenduidig verlopen registratie en declaratie?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_standardization_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "care",
    category: "Branchespecifiek",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Werkt iedereen vanuit dezelfde werkwijze?",
      "Of verschilt dit per team of locatie?",
    ],
    visibleWhen: [{ field: "sector", operator: "equals", value: "zorg" }],
  },

  {
    key: "education_intake_planning_consistency",
    sectionCode: "diagnose",
    order: 410,
    label: "Eenduidigheid van intake en planning",
    helpText: "Kies hoe eenduidig intake, planning en verwerking verlopen.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_standardization_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "education",
    category: "Branchespecifiek",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan intake, inschrijving en planning",
      "Werkt iedereen vanuit dezelfde route?",
    ],
    visibleWhen: [{ field: "sector", operator: "equals", value: "onderwijs" }],
  },
  {
    key: "education_process_admin_alignment",
    sectionCode: "diagnose",
    order: 420,
    label: "Aansluiting tussen onderwijsproces en administratie",
    helpText: "Kies hoe goed uitvoering en administratie op elkaar aansluiten.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_fit_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "education",
    category: "Branchespecifiek",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan planning, deelnemers en facturatie",
      "Ontstaan fouten vooral bij de overdracht?",
    ],
    visibleWhen: [
      { field: "sector", operator: "equals", value: "onderwijs" },
    ],
  },
  {
    key: "education_exception_handling",
    sectionCode: "diagnose",
    order: 430,
    label: "Uitzonderingen in traject- of cursusadministratie",
    helpText: "Kies hoe beheersbaar deze afwijkingen nu zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_exception_control_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "education",
    category: "Branchespecifiek",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan last-minute wijzigingen of correcties",
      "Zijn afwijkingen voorzien of vooral ad hoc opgelost?",
    ],
    visibleWhen: [{ field: "sector", operator: "equals", value: "onderwijs" }],
  },

  {
    key: "crm_strategic_pressure",
    sectionCode: "diagnose",
    order: 510,
    label: "Waar ervaar je nu de meeste problemen binnen CRM?",
    helpText: "Kies waar binnen CRM nu de meeste druk zit.",
    inputType: "single_select",
    required: true,
    optionSetKey: "crm_strategic_pressure_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "crm",
    category: "AFAS Modules",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Leadbeheer, pipeline of relatiebeheer?",
      "Kies wat nu het meeste effect heeft",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "crm" },
    ],
  },
  {
    key: "crm_process_maturity",
    sectionCode: "diagnose",
    order: 520,
    label: "Eenduidigheid van CRM-werkwijze",
    helpText: "Kies hoe eenduidig CRM nu wordt gebruikt in de organisatie.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_standardization_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "crm",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan vastleggen van leads, contactmomenten en kansen",
      "Werkt iedereen op dezelfde manier of sterk verschillend?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "crm" },
    ],
  },
  {
    key: "crm_data_quality",
    sectionCode: "diagnose",
    order: 530,
    label: "Kwaliteit van CRM-gegevens",
    helpText: "Kies hoe betrouwbaar en bruikbaar de CRM-gegevens nu zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_usefulness_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "crm",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan volledigheid, actualiteit en eenduidigheid van relaties en kansen",
      "Kun je op de gegevens vertrouwen voor opvolging en sturing?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "crm" },
    ],
  },
  {
    key: "crm_reporting_usefulness",
    sectionCode: "diagnose",
    order: 540,
    label: "Bruikbaarheid van commerciële stuurinformatie",
    helpText: "Kies hoe bruikbaar CRM-informatie nu is voor commerciële sturing.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_usefulness_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "crm",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan pipeline, forecast en inzicht in commerciële voortgang",
      "Kun je hier echt op sturen?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "crm" },
      {
        field: "scope_focus",
        operator: "includes",
        value: "rapportage_sturing",
      },
    ],
  },

  {
    key: "hrm_strategic_pressure",
    sectionCode: "diagnose",
    order: 710,
    label: "Waar ervaar je nu de meeste problemen binnen HRM?",
    helpText: "Kies waar binnen HRM nu de meeste druk zit.",
    inputType: "single_select",
    required: true,
    optionSetKey: "hrm_strategic_pressure_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "hrm",
    category: "AFAS Modules",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Mutaties, dossieropbouw of selfservice?",
      "Kies wat nu het meeste effect heeft",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "hrm" },
    ],
  },
  {
    key: "hrm_process_maturity",
    sectionCode: "diagnose",
    order: 720,
    label: "Eenduidigheid van HRM-processen",
    helpText: "Kies hoe eenduidig HRM-processen nu verlopen.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_standardization_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "hrm",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan in-, door- en uitstroom en mutatieverwerking",
      "Werkt iedereen vanuit dezelfde route?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "hrm" },
    ],
  },
  {
    key: "hrm_data_quality",
    sectionCode: "diagnose",
    order: 730,
    label: "Kwaliteit van HRM-vastlegging",
    helpText: "Kies hoe betrouwbaar en volledig HRM-gegevens en dossiers nu zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_usefulness_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "hrm",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan volledigheid van gegevens, dossiers en mutaties",
      "Is de vastlegging bruikbaar voor proces en controle?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "hrm" },
    ],
  },

  {
    key: "reporting_strategic_pressure",
    sectionCode: "diagnose",
    order: 810,
    label: "Waar ervaar je nu de meeste problemen binnen rapportage?",
    helpText: "Kies waar nu de meeste druk zit in rapportage en stuurinformatie.",
    inputType: "single_select",
    required: true,
    optionSetKey: "reporting_strategic_pressure_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "reporting",
    category: "Rapportage & Data",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Definities, betrouwbaarheid of bruikbaarheid?",
      "Kies wat nu het meeste effect heeft",
    ],
    visibleWhen: [
      {
        field: "afas_products",
        operator: "includes",
        value: "rapportage_dashboards",
      },
    ],
  },
  {
    key: "reporting_definition_consistency",
    sectionCode: "diagnose",
    order: 820,
    label: "Eenduidigheid van definities en KPI's",
    helpText: "Kies hoe eenduidig KPI's, definities en rapportagelogica nu zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_clarity_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "reporting",
    category: "Rapportage & Data",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan omzet, marge, forecast en andere stuurgetallen",
      "Is duidelijk wat iedereen onder dezelfde cijfers verstaat?",
    ],
    visibleWhen: [
      {
        field: "afas_products",
        operator: "includes",
        value: "rapportage_dashboards",
      },
      {
        field: "scope_focus",
        operator: "includes",
        value: "rapportage_sturing",
      },
    ],
  },
  {
    key: "reporting_usefulness",
    sectionCode: "diagnose",
    order: 830,
    label: "Bruikbaarheid van rapportage voor sturing",
    helpText: "Kies hoe bruikbaar rapportages nu zijn voor besluitvorming en sturing.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_usefulness_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "reporting",
    category: "Rapportage & Data",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan actualiteit, betrouwbaarheid en gebruik in de praktijk",
      "Kun je hier echt op sturen?",
    ],
    visibleWhen: [
      {
        field: "afas_products",
        operator: "includes",
        value: "rapportage_dashboards",
      },
    ],
  },

  {
    key: "integration_strategic_pressure",
    sectionCode: "diagnose",
    order: 910,
    label: "Waar ervaar je nu de meeste problemen met integraties?",
    helpText:
      "Kies waar nu de meeste druk zit in koppelingen en gegevensuitwisseling.",
    inputType: "single_select",
    required: true,
    optionSetKey: "integration_strategic_pressure_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "integrations",
    category: "Rapportage & Data",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Stabiliteit, eigenaarschap of monitoring?",
      "Kies wat nu het meeste effect heeft",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "integraties" },
    ],
  },
  {
    key: "integration_stability",
    sectionCode: "diagnose",
    order: 920,
    label: "Stabiliteit van koppelingen",
    helpText: "Kies hoe stabiel koppelingen en gegevensuitwisseling nu zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_strength_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "integrations",
    category: "Rapportage & Data",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan uitval, verstoringen en handmatig herstel",
      "Is de keten stabiel genoeg voor de operatie?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "integraties" },
    ],
  },
  {
    key: "integration_ownership",
    sectionCode: "diagnose",
    order: 930,
    label: "Duidelijkheid van eigenaarschap op integraties",
    helpText:
      "Kies hoe duidelijk eigenaarschap en verantwoordelijkheid op koppelingen nu is.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_clarity_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "integrations",
    category: "Rapportage & Data",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan wie eigenaar is van werking, wijzigingen en opvolging",
      "Is duidelijk wie moet handelen bij uitval of wijziging?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "integraties" },
    ],
  },
  {
    key: "integration_monitoring_maturity",
    sectionCode: "diagnose",
    order: 940,
    label: "Monitoring en opvolging van koppelingen",
    helpText: "Kies hoe goed koppelingen nu worden bewaakt en opgevolgd.",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_improvement_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "integrations",
    category: "Rapportage & Data",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan signalering, logging en opvolging van fouten",
      "Worden problemen actief bewaakt en opgepakt?",
    ],
    visibleWhen: [
      { field: "afas_products", operator: "includes", value: "integraties" },
      {
        field: "scope_focus",
        operator: "includes",
        value: "beheer_doorontwikkeling",
      },
    ],
  },

  // ==========================================
  // NIEUWE VRAGEN - Diagnoseverdieping
  // ==========================================

  // Vraag 3: Waar verliest de organisatie tijd
  {
    key: "time_loss_areas",
    sectionCode: "diagnose",
    order: 950,
    label: "Waar verliest de organisatie nu de meeste tijd?",
    helpText: "Selecteer alles wat van toepassing is.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "time_loss_areas_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "process_efficiency",
    category: "Organisatie & Beheer",
    outputRole: "evidence",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Denk aan dagelijkse frustraties en tijdvreters",
      "Waar gaat onnodig veel tijd aan op?",
    ],
  },

  // Vraag 4: Buiten AFAS werken frequentie
  {
    key: "outside_afas_frequency",
    sectionCode: "diagnose",
    order: 960,
    label: "Hoe vaak wordt er buiten AFAS om gewerkt?",
    helpText: "Kies wat het beste de situatie beschrijft.",
    inputType: "single_select",
    required: true,
    optionSetKey: "outside_afas_frequency_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "system_fit",
    category: "AFAS Modules",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan Excel, mail of losse lijsten",
      "Hoe vaak zijn workarounds nodig?",
    ],
  },

  // Vraag 5: Reden buiten AFAS werken
  {
    key: "outside_afas_reasons",
    sectionCode: "diagnose",
    order: 970,
    label: "Wat is meestal de reden dat buiten AFAS om wordt gewerkt?",
    helpText: "Selecteer alles wat van toepassing is.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "outside_afas_reasons_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "system_fit",
    category: "AFAS Modules",
    outputRole: "evidence",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Wat zijn de belangrijkste redenen?",
      "Selecteer ook als meerdere redenen spelen",
    ],
  },

  // Vraag 6: Backlog/verbeterlijst maturity
  {
    key: "backlog_maturity",
    sectionCode: "diagnose",
    order: 980,
    label: "Is er een centrale verbeterlijst of backlog?",
    helpText: "Kies wat het beste de situatie beschrijft.",
    inputType: "single_select",
    required: true,
    optionSetKey: "backlog_maturity_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "governance",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Worden verbeterpunten centraal bijgehouden?",
      "Is er een gedeelde backlog met prioriteiten?",
    ],
  },

  // Vraag 7: Wie bepaalt aanpassingen
  {
    key: "change_decision_owner",
    sectionCode: "diagnose",
    order: 990,
    label: "Wie bepaalt uiteindelijk of een proces of AFAS-inrichting wordt aangepast?",
    helpText: "Kies wie nu de beslissingen neemt.",
    inputType: "single_select",
    required: true,
    optionSetKey: "change_decision_owner_options",
    allowsComment: true,
    dimensionCode: "governance",
    category: "Organisatie & Beheer",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Wie heeft het laatste woord bij wijzigingen?",
      "Is dit duidelijk of wisselt dit per situatie?",
    ],
  },

  // Vraag 8: Stamdata betrouwbaarheid
  {
    key: "master_data_reliability",
    sectionCode: "diagnose",
    order: 1000,
    label: "Hoe betrouwbaar is de stamdata in AFAS?",
    helpText: "Kies wat het beste de datakwaliteit beschrijft.",
    inputType: "single_select",
    required: true,
    optionSetKey: "master_data_reliability_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "data_quality",
    category: "Rapportage & Data",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Denk aan volledigheid, actualiteit en dubbelingen",
      "Kun je vertrouwen op de basisgegevens?",
    ],
  },

  // Vraag 9: Welke stamdata geeft problemen
  {
    key: "master_data_problems",
    sectionCode: "diagnose",
    order: 1010,
    label: "Welke stamdata geeft de meeste problemen?",
    helpText: "Selecteer alles wat van toepassing is.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "master_data_problems_options",
    allowsComment: true,
    minDepthLevel: "verbeterplan",
    dimensionCode: "data_quality",
    category: "Rapportage & Data",
    outputRole: "evidence",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Welke gegevensgroepen zijn het minst betrouwbaar?",
      "Waar zitten de meeste fouten of hiaten?",
    ],
  },

  // Vraag 10: AFAS adoptie niveau
  {
    key: "afas_adoption_level",
    sectionCode: "diagnose",
    order: 1020,
    label: "Hoe goed gebruiken medewerkers AFAS zoals bedoeld?",
    helpText: "Kies wat het beste de adoptie beschrijft.",
    inputType: "single_select",
    required: true,
    optionSetKey: "afas_adoption_level_options",
    allowsComment: true,
    minDepthLevel: "gericht_verdiepen",
    dimensionCode: "adoption",
    category: "Organisatie & Beheer",
    outputRole: "score",
    scoreEnabled: true,
    scoreWeight: 1,
    examples: [
      "Wordt AFAS consequent en correct gebruikt?",
      "Of zijn er veel workarounds en verschillen?",
    ],
  },

  // Vraag 11: Adoptie barrières
  {
    key: "adoption_barriers",
    sectionCode: "diagnose",
    order: 1030,
    label: "Wat belemmert goed gebruik van AFAS het meest?",
    helpText: "Selecteer alles wat van toepassing is.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "adoption_barriers_options",
    allowsComment: true,
    minDepthLevel: "verbeterplan",
    dimensionCode: "adoption",
    category: "Organisatie & Beheer",
    outputRole: "evidence",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Denk aan kennis, tijd, eigenaarschap of inrichting",
      "Wat houdt beter gebruik tegen?",
    ],
  },

  // Vraag 12: Meest waardevolle verbetering
  {
    key: "most_valuable_improvement",
    sectionCode: "diagnose",
    order: 1040,
    label: "Welke verbetering zou de meeste waarde opleveren?",
    helpText: "Kies wat het meeste impact zou hebben.",
    inputType: "single_select",
    required: true,
    optionSetKey: "most_valuable_improvement_options",
    allowsComment: true,
    dimensionCode: "improvement_focus",
    category: "Organisatie & Beheer",
    outputRole: "context",
    scoreEnabled: false,
    scoreWeight: 0,
    examples: [
      "Als je één ding zou verbeteren, wat dan?",
      "Wat zou het meeste verschil maken?",
    ],
  },
];
