import type { QuestionDefinition } from "../types";

export const questions: QuestionDefinition[] = [
  {
    key: "customer_name",
    sectionCode: "profile_basis",
    order: 10,
    label: "Klantnaam",
    helpText: "Vul de naam van de organisatie in.",
    inputType: "text",
    required: true,
    placeholder: "Bijvoorbeeld: Janssen BV",
  },
  {
    key: "sector",
    sectionCode: "profile_basis",
    order: 20,
    label: "Sector",
    helpText: "Kies de sector die het beste past bij de organisatie.",
    inputType: "single_select",
    required: true,
    optionSetKey: "sector_options",
    examples: [
      "Bijvoorbeeld: zorg, onderwijs of commercieel.",
      "Kies de sector die het meest bepalend is voor processen en inrichting.",
    ],
  },
  {
    key: "organization_size",
    sectionCode: "profile_basis",
    order: 30,
    label: "Organisatiegrootte",
    helpText: "Geef aan hoe groot de organisatie ongeveer is.",
    inputType: "single_select",
    required: true,
    optionSetKey: "organization_size_options",
    examples: [
      "Denk aan het totaal aantal medewerkers dat binnen de organisatie werkt.",
      "Kies de klasse die het best past bij de huidige omvang van de organisatie.",
    ],
  },
  {
    key: "administration_count",
    sectionCode: "profile_basis",
    order: 40,
    label: "Aantal administraties / entiteiten",
    helpText: "Kies hoeveel administraties of entiteiten ongeveer in scope zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "administration_count_options",
    examples: [
      "Denk aan aparte administraties, bv’s of andere juridische entiteiten.",
      "Kies wat het best past bij het deel van de organisatie dat je wilt beoordelen.",
    ],
  },
  {
    key: "afas_products",
    sectionCode: "profile_basis",
    order: 50,
    label: "Gebruikte AFAS-onderdelen",
    helpText:
      "Welke AFAS-onderdelen zijn nu in gebruik of relevant voor deze scan? Kies alles wat van toepassing is.",
    inputType: "multi_select",
    required: false,
    optionSetKey: "afas_products_options",
    examples: [
      "Bijvoorbeeld: Financieel, HRM, Inkoop, Ordermanagement of Workflow.",
      "Kies ook onderdelen die al wel relevant zijn voor de scan, ook als ze nog niet volledig worden benut.",
    ],
  },
  {
    key: "scan_reason",
    sectionCode: "profile_reason",
    order: 10,
    label: "Aanleiding en doel van de scan",
    helpText:
      "Wat is de belangrijkste reden om deze scan nu te doen en wat moet deze opleveren?",
    inputType: "single_select",
    required: true,
    optionSetKey: "scan_reason_options",
    examples: [
      "Bijvoorbeeld: nulmeting, optimalisatie, herinrichting of voorbereiding op groei.",
      "Kies de reden die nu het zwaarst weegt voor deze scan.",
    ],
  },
  {
    key: "biggest_bottleneck",
    sectionCode: "profile_reason",
    order: 20,
    label: "Belangrijkste knelpunten op dit moment",
    helpText:
      "Welke onderwerpen veroorzaken nu de meeste frictie of onduidelijkheid? Kies maximaal 3.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "biggest_bottleneck_options",
    maxSelections: 3,
    examples: [
      "Bijvoorbeeld: processen lopen niet eenduidig, eigenaarschap is onduidelijk of rapportages geven te weinig grip.",
      "Kies alleen de onderwerpen die nu echt de meeste druk of onrust veroorzaken.",
    ],
  },
  {
    key: "scope",
    sectionCode: "scope",
    order: 10,
    label: "Breedte van de scan",
    helpText: "Kies hoe breed je de scan wilt uitvoeren.",
    inputType: "single_select",
    required: true,
    optionSetKey: "scope_options",
    examples: [
      "Smal: gericht op een beperkt aantal onderwerpen.",
      "Breed: meerdere domeinen en processen in samenhang bekijken.",
    ],
  },
  {
    key: "scope_focus",
    sectionCode: "scope",
    order: 20,
    label: "Belangrijkste focusgebieden",
    helpText: "Welke onderwerpen vragen nu de meeste aandacht? Kies maximaal 2.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "scope_focus_options",
    maxSelections: 2,
    examples: [
      "Bijvoorbeeld: processen en werkwijze, AFAS-inrichting en gebruik, of rapportage en sturing.",
      "Kies de gebieden waar de scan bewust extra scherpte op moet aanbrengen.",
    ],
  },
  {
    key: "scope_depth",
    sectionCode: "scope",
    order: 30,
    label: "Gewenst detailniveau",
    helpText: "Hoe diep wil je in deze scan kijken?",
    inputType: "single_select",
    required: true,
    optionSetKey: "scope_depth_options",
    examples: [
      "Snel eerste beeld: vooral richting en hoofdlijnen.",
      "Basis voor concreet verbeterplan: meer detail en meer houvast voor opvolging.",
    ],
  },
  {
    key: "ownership_clarity",
    sectionCode: "diagnose",
    order: 10,
    label: "Eigenaarschap van processen en inrichting",
    helpText: "Hoe duidelijk is het eigenaarschap van processen en inrichting?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_clarity_options",
    allowsComment: true,
    examples: [
      "Bijvoorbeeld: is duidelijk wie beslist over wijzigingen in processen of AFAS?",
      "Denk aan: wie is eigenaar van orderverwerking, facturatie, inkoop of HR-processen?",
    ],
  },
  {
    key: "change_decision_process",
    sectionCode: "diagnose",
    order: 20,
    label: "Besluitvorming over wijzigingen",
    helpText:
      "Hoe gestructureerd worden wijzigingen in processen of AFAS besloten?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_change_governance_options",
    allowsComment: true,
    examples: [
      "Bijvoorbeeld: worden wijzigingen besproken in een vast overleg of vooral ad hoc doorgevoerd?",
      "Denk aan: is er een duidelijke route voor wijzigingsverzoeken en besluiten?",
   
