import type { QuestionDefinition } from "../types";

export const questions: QuestionDefinition[] = [
  {
    key: "customer_name",
    sectionCode: "profile_basis",
    order: 10,
    label: "Klantnaam",
    helpText: "Vul de naam van de organisatie in.",
    inputType: "text",
    required: true,
    placeholder: "Bijvoorbeeld: Janssen BV",
  },
  {
    key: "sector",
    sectionCode: "profile_basis",
    order: 20,
    label: "Sector",
    helpText: "Kies de sector die het beste past bij de organisatie.",
    inputType: "single_select",
    required: true,
    optionSetKey: "sector_options",
  },
  {
    key: "organization_size",
    sectionCode: "profile_basis",
    order: 30,
    label: "Organisatiegrootte",
    helpText: "Geef aan hoe groot de organisatie ongeveer is.",
    inputType: "single_select",
    required: true,
    optionSetKey: "organization_size_options",
  },
  {
    key: "administration_count",
    sectionCode: "profile_basis",
    order: 40,
    label: "Aantal administraties / entiteiten",
    helpText: "Kies hoeveel administraties of entiteiten ongeveer in scope zijn.",
    inputType: "single_select",
    required: true,
    optionSetKey: "administration_count_options",
  },
  {
    key: "afas_products",
    sectionCode: "profile_basis",
    order: 50,
    label: "Gebruikte AFAS-onderdelen",
    helpText:
      "Welke AFAS-onderdelen zijn nu in gebruik of relevant voor deze scan? Kies alles wat van toepassing is.",
    inputType: "multi_select",
    required: false,
    optionSetKey: "afas_products_options",
  },
  {
    key: "scan_reason",
    sectionCode: "profile_reason",
    order: 10,
    label: "Aanleiding en doel van de scan",
    helpText:
      "Wat is de belangrijkste reden om deze scan nu te doen en wat moet deze opleveren?",
    inputType: "single_select",
    required: true,
    optionSetKey: "scan_reason_options",
  },
  {
    key: "biggest_bottleneck",
    sectionCode: "profile_reason",
    order: 20,
    label: "Belangrijkste knelpunten op dit moment",
    helpText:
      "Welke onderwerpen veroorzaken nu de meeste frictie of onduidelijkheid? Kies maximaal 3.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "biggest_bottleneck_options",
    maxSelections: 3,
  },
  {
    key: "scope",
    sectionCode: "scope",
    order: 10,
    label: "Breedte van de scan",
    helpText: "Kies hoe breed je de scan wilt uitvoeren.",
    inputType: "single_select",
    required: true,
    optionSetKey: "scope_options",
  },
  {
    key: "scope_focus",
    sectionCode: "scope",
    order: 20,
    label: "Belangrijkste focusgebieden",
    helpText: "Welke onderwerpen vragen nu de meeste aandacht? Kies maximaal 2.",
    inputType: "multi_select",
    required: true,
    optionSetKey: "scope_focus_options",
    maxSelections: 2,
  },
  {
    key: "scope_depth",
    sectionCode: "scope",
    order: 30,
    label: "Gewenst detailniveau",
    helpText: "Hoe diep wil je in deze scan kijken?",
    inputType: "single_select",
    required: true,
    optionSetKey: "scope_depth_options",
  },
  {
    key: "ownership_clarity",
    sectionCode: "diagnose",
    order: 10,
    label: "Eigenaarschap van processen en inrichting",
    helpText: "Hoe duidelijk is het eigenaarschap van processen en inrichting?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_clarity_options",
    allowsComment: true,
  },
  {
    key: "change_decision_process",
    sectionCode: "diagnose",
    order: 20,
    label: "Besluitvorming over wijzigingen",
    helpText:
      "Hoe gestructureerd worden wijzigingen in processen of AFAS besloten?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_change_governance_options",
    allowsComment: true,
  },
  {
    key: "improvement_governance",
    sectionCode: "diagnose",
    order: 30,
    label: "Sturing op verbetering",
    helpText:
      "In welke mate wordt actief gestuurd op verbetering van processen en inrichting?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_improvement_options",
    allowsComment: true,
  },
  {
    key: "process_standardization",
    sectionCode: "diagnose",
    order: 40,
    label: "Eenduidigheid van werkwijze",
    helpText: "Hoe eenduidig worden de belangrijkste processen uitgevoerd?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_standardization_options",
    allowsComment: true,
  },
  {
    key: "exception_control",
    sectionCode: "diagnose",
    order: 50,
    label: "Omgaan met uitzonderingen",
    helpText: "Hoe beheersbaar zijn uitzonderingen binnen de processen?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_exception_control_options",
    allowsComment: true,
  },
  {
    key: "issue_resolution",
    sectionCode: "diagnose",
    order: 60,
    label: "Structureel oplossen van knelpunten",
    helpText: "Hoe worden terugkerende fouten of knelpunten meestal aangepakt?",
    inputType: "single_select",
    required: true,
    optionSetKey: "maturity_3level_issue_resolution_options",
    allowsComment: true,
  },
];
