import type { SectionDefinition } from "../types";

export const sections: SectionDefinition[] = [
  {
    code: "profile_basis",
    title: "Stap 1 van 6 — Organisatieprofiel",
    shortTitle: "Organisatie",
    description: "Eerst leggen we de basiscontext van de organisatie vast. Dit helpt om de scan gericht te maken.",
    phase: "profile",
    order: 10,
    summaryEnabled: false,
    nextSectionCode: "profile_afas",
  },
  {
    code: "profile_afas",
    title: "Stap 2 van 6 — AFAS-context",
    shortTitle: "AFAS",
    description: "Daarna bepalen we welke onderdelen, processen en knelpunten relevant zijn voor deze organisatie.",
    phase: "profile",
    order: 15,
    summaryEnabled: false,
    nextSectionCode: "profile_reason",
  },
  {
    code: "profile_reason",
    title: "Stap 3 van 6 — Aanleiding",
    shortTitle: "Aanleiding",
    description: "Wat is de aanleiding voor deze scan en waar liggen de belangrijkste knelpunten?",
    phase: "profile",
    order: 20,
    summaryEnabled: false,
    nextSectionCode: "scope",
  },
  {
    code: "scope",
    title: "Stap 4 van 6 — Scope",
    shortTitle: "Scope",
    description: "Bepaal de breedte en diepte van de scan.",
    phase: "scope",
    order: 30,
    summaryEnabled: false,
    nextSectionCode: "diagnose",
  },
  {
    code: "diagnose",
    title: "Stap 5 van 6 — Diagnose",
    shortTitle: "Diagnose",
    description: "Beoordeel de belangrijkste domeinen en processen.",
    phase: "diagnose",
    order: 40,
    summaryEnabled: false,
    nextSectionCode: "advies",
  },
  {
    code: "advies",
    title: "Stap 6 van 6 — Advies",
    shortTitle: "Advies",
    description: "Bekijk de adviesrichting en prioriteiten.",
    phase: "advies",
    order: 50,
    summaryEnabled: true,
  },
];
