export type InputType = "text" | "single_select" | "multi_select";

export type VisibilityOperator = "equals" | "includes" | "one_of";

export type VisibilityRule = {
  field: string;
  operator: VisibilityOperator;
  value: string | string[];
};

export type OptionDefinition = {
  value: string;
  label: string;
  order: number;
  description?: string;
};

export type OptionSetDefinition = {
  key: string;
  options: OptionDefinition[];
};

export type SectionDefinition = {
  code: string;
  title: string;
  shortTitle: string;
  description?: string;
  phase: string;
  order: number;
  summaryEnabled: boolean;
  nextSectionCode?: string;
};

export type QuestionDefinition = {
  key: string;
  sectionCode: string;
  order: number;
  label: string;
  helpText?: string;
  inputType: InputType;
  required: boolean;
  placeholder?: string;
  optionSetKey?: string;
  examples?: string[];
  allowsComment?: boolean;
  domain?: string;
  category?: string;
  maxSelections?: number;
  visibleWhen?: VisibilityRule[];
};

export type ScanDefinition = {
  sections: SectionDefinition[];
  questions: QuestionDefinition[];
  optionSets: OptionSetDefinition[];
};

// Pillar Score Types
export type SubDimensionScore = {
  code: string;
  label: string;
  score: number; // 1-5
  questionCount: number;
  answeredCount: number;
};

export type PillarScore = {
  code: string;
  label: string;
  description: string;
  color: string;
  score: number; // 1-5 (average of sub-dimensions)
  subDimensions: SubDimensionScore[];
};

export type TotalScore = {
  score: number; // 1-5 (weighted average)
  pillars: PillarScore[];
};

// Roadmap Types
export type RoadmapPriority = "high" | "medium" | "low";
export type RoadmapQuarter = "Q1" | "Q2" | "Q3" | "Q4";
export type RoadmapYear = 1 | 2 | 3;

export type RoadmapItem = {
  id: string;
  pillarCode: string;
  subDimensionCode: string;
  title: string;
  description: string;
  currentLevel: number;
  targetLevel: number;
  quarter: RoadmapQuarter;
  year: RoadmapYear;
  priority: RoadmapPriority;
  isAutoGenerated: boolean;
  isCompleted: boolean;
};

export type Roadmap = {
  items: RoadmapItem[];
  lastModified: string;
};
